---
dependency:
  name: galaxy
driver:
  name: delegated

platforms:
  - name: ubuntu1804-1
    template_name: ubuntu-18-04
    groups:
      - docker_manager

  - name: ubuntu1804-2
    template_name: ubuntu-18-04
    groups:
      - docker_manager

  - name: ubuntu1804-3
    template_name: ubuntu-18-04
    groups:
      - docker_manager

  - name: ubuntu1804-4
    template_name: ubuntu-18-04
    groups:
      - docker_worker

  - name: ubuntu1804-5
    template_name: ubuntu-18-04
    groups:
      - docker_worker
      - scale_down_host
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    prepare: ../default-install/converge.yml
    destroy: ../default/destroy.yml
    converge: ../default-scaledown/converge.yml
    verify: ../default-scaledown/verify.yml

verifier:
  name: ansible
