---
- assert:
    that: item is defined

- name: "Get Container Facts"
  community.docker.docker_container_info:
    name: "{{ item }}"
  register: container_facts

- name: Add Container Fact to list
  set_fact:
    container_facts_list: "{{ container_facts_list | default([]) + [ container_facts ] }}"