---
dependency:
  name: galaxy
driver:
  name: delegated

platforms:
  - name: centos8-1
    image_name: ansible-dev-centos-8-stream
    groups:
      - docker_manager

  - name: centos8-2
    image_name: ansible-dev-centos-8-stream
    groups:
      - docker_manager

  - name: centos8-3
    image_name: ansible-dev-centos-8-stream
    groups:
      - docker_manager

  - name: centos8-4
    image_name: ansible-dev-centos-8-stream
    groups:
      - docker_worker

  - name: centos8-5
    image_name: ansible-dev-centos-8-stream
    groups:
      - docker_worker
      - scale_down_host
provisioner:
  name: ansible
  playbooks:
    create: ../default/create-os.yml
    destroy: ../default/destroy-os.yml
    prepare: ../default-install/converge.yml
    converge: ../default-scaledown/converge.yml
    verify: ../default-scaledown/verify.yml

verifier:
  name: ansible
