---
- name: "Check required variables"
  assert:
    that: "{{ item.name }} is defined"
    fail_msg: "Missing variable '{{ item.name }}': {{ item.description }}"
  with_items:
    - { name: "service_id",             description: "Id of the service instance that will be deployed." }

- name: "Get Service names from namespace '{{ service_id }}'"
  ansible.builtin.shell: "docker service ls --filter 'label=com.docker.stack.namespace={{ service_id }}' --format {%raw%}{{.Name}}{%endraw%}"
  register: get_services_output
  changed_when: false

- name: Extract service names from 'docker service ls'
  set_fact:
    service_names: "{{ get_services_output.stdout_lines }}"

- name: "Get Volume names from namespace '{{ service_id }}'"
  ansible.builtin.shell: "docker volume ls --filter 'label=com.docker.stack.namespace={{ service_id }}' --format {%raw%}{{.Name}}{%endraw%}"
  register: get_volume_output
  changed_when: false

- name: Extract volume names from 'docker volume ls'
  set_fact:
    volume_names: "{{ get_volume_output.stdout_lines }}"

- name: Undeploy Stack
  docker_stack:
    state: absent
    name: "{{ service_id }}"
  run_once: true

- name: "Remove Volumes"
  community.docker.docker_volume:
    name: "{{ item }}"
    state: absent
  loop: "{{ volume_names }}"
  when: volume_names | default([]) | length > 0
  register: delete_volume_result
  until: delete_volume_result.changed == true
  retries: 50
  delay: 2