---
collections:
  - name: "https://github.com/eclipse-slm/slm-dc-docker"
    type: git
    version: develop

roles:
  - src: "git+https://github.com/FabOS-AI/molecule_vsphere.git"
    scm: git
    version: develop
    name: molecule_vsphere