---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Create via openstack
      ansible.builtin.include_role:
        name: molecule_openstack
        tasks_from: create.yml
