---
dependency:
  name: galaxy
driver:
  name: delegated

platforms:
  - name: ubuntu2004-1
    image_name: ansible-dev-ubuntu-20-04
    groups:
      - docker_manager

  - name: ubuntu2004-2
    image_name: ansible-dev-ubuntu-20-04
    groups:
      - docker_manager

  - name: ubuntu2004-3
    image_name: ansible-dev-ubuntu-20-04
    groups:
      - docker_manager

  - name: ubuntu2004-4
    image_name: ansible-dev-ubuntu-20-04
    groups:
      - docker_worker
provisioner:
  name: ansible
  playbooks:
    create: ../../../setup/molecule/default/create-os.yml
    destroy: ../../../setup/molecule/default/destroy-os.yml
    prepare: ../../../setup/molecule/default-install/converge.yml
    converge: ../default-deploy/converge.yml
    verify: ../default-deploy/verify.yml

verifier:
  name: ansible
