---
dependency:
  name: galaxy
driver:
  name: delegated

platforms:
  - name: centos7-1
    image_name: ansible-dev-centos-7
    groups:
      - docker_manager

  - name: centos7-2
    image_name: ansible-dev-centos-7
    groups:
      - docker_manager

  - name: centos7-3
    image_name: ansible-dev-centos-7
    groups:
      - docker_manager

  - name: centos7-4
    image_name: ansible-dev-centos-7
    groups:
      - docker_worker
provisioner:
  name: ansible
  playbooks:
    create: ../../../setup/molecule/default/create-os.yml
    destroy: ../../../setup/molecule/default/destroy-os.yml
    prepare: ../default-undeploy/prepare.yml
    converge: ../default-undeploy/converge.yml
    verify: ../default-undeploy/verify.yml

verifier:
  name: ansible
