---
dependency:
  name: galaxy
driver:
  name: delegated

platforms:
  - name: ubuntu2204-1
    template_name: ubuntu-22-04
    groups:
      - docker_manager

  - name: ubuntu2204-2
    template_name: ubuntu-22-04
    groups:
      - docker_manager

  - name: ubuntu2204-3
    template_name: ubuntu-22-04
    groups:
      - docker_manager

  - name: ubuntu2204-4
    template_name: ubuntu-22-04
    groups:
      - docker_worker

  - name: ubuntu2204-5
    template_name: ubuntu-22-04
    groups:
      - docker_worker
      - scale_up_host
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    prepare: ../default-install/converge.yml
    destroy: ../default/destroy.yml
    converge: ../default-scaleup/converge.yml
    verify: ../default-scaleup/verify.yml

verifier:
  name: ansible
