---
dependency:
  name: galaxy
driver:
  name: delegated

platforms:
  - name: ubuntu1804-1
    template_name: ubuntu-18-04
    groups:
      - docker_manager

  - name: ubuntu1804-2
    template_name: ubuntu-18-04
    groups:
      - docker_manager

  - name: ubuntu1804-3
    template_name: ubuntu-18-04
    groups:
      - docker_manager

  - name: ubuntu1804-4
    template_name: ubuntu-18-04
    groups:
      - docker_worker
provisioner:
  name: ansible
  playbooks:
    create: ../../../setup/molecule/default/create.yml
    prepare: ../default-undeploy/prepare.yml
    destroy: ../../../setup/molecule/default/destroy.yml
    converge: ../default-undeploy/converge.yml
    verify: ../default-undeploy/verify.yml

verifier:
  name: ansible
