---
dependency:
  name: galaxy
driver:
  name: delegated

platforms:
  - name: centos7-1
    template_name: centos-7
    groups:
      - docker_manager

  - name: centos7-2
    template_name: centos-7
    groups:
      - docker_manager

  - name: centos7-3
    template_name: centos-7
    groups:
      - docker_manager

  - name: centos7-4
    template_name: centos-7
    groups:
      - docker_worker

  - name: centos7-5
    template_name: centos-7
    groups:
      - docker_worker
      - scale_up_host
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    prepare: ../default-install/converge.yml
    destroy: ../default/destroy.yml
    converge: ../default-scaleup/converge.yml
    verify: ../default-scaleup/verify.yml

verifier:
  name: ansible
