---
- name: Converge - Leave Swarm and Uninstall docker
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: "Include fabos.docker_swarm.setup - uninstall"
      ansible.builtin.include_role:
        name: setup
        tasks_from: uninstall.yml

    - name: "Include docker role - uninstall"
      ansible.builtin.include_role:
        name: docker
      vars:
        state: absent