- name: Populate service facts
  ansible.builtin.service_facts:

- name: "Add firewall rules"
  when:
    - ansible_facts.services['firewalld.service'] is defined
    - ansible_facts.services['firewalld.service'].status != 'not-found'
  block:
    - name: "Add rule"
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - 2376/tcp
        - 2377/tcp
        - 7946/tcp
        - 7946/udp
        - 4789/udp
      register: add_firewall_rule

    - name: Restart services
      when: add_firewall_rule.changed
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: "{{ item }}"
      loop:
        - firewalld
        - docker