---
- name: Set IP Address of Host
  set_fact:
    host_ip_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: Get Manager Token
  ansible.builtin.shell: docker swarm join-token -q manager
  changed_when: false
  register: docker_swarm_join_token_manager_shell

- name: Get Worker Token
  ansible.builtin.shell: docker swarm join-token -q worker
  changed_when: false
  register: docker_swarm_join_token_worker_shell

- set_fact:
    docker_swarm_join_token_manager: "{{ docker_swarm_join_token_manager_shell.stdout }}"
    docker_swarm_join_token_worker: "{{ docker_swarm_join_token_worker_shell.stdout }}"

- set_fact:
    docker_swarm_join_token_manager: "{{ docker_swarm_join_token_manager_shell.stdout }}"
    docker_swarm_join_token_worker: "{{ docker_swarm_join_token_worker_shell.stdout }}"
    docker_swarm_manager_ip: "{{ host_ip_address }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['all']}}"

- set_fact:
    docker_swarm_join_token_manager: "{{ docker_swarm_join_token_manager_shell.stdout }}"
    docker_swarm_join_token_worker: "{{ docker_swarm_join_token_worker_shell.stdout }}"
  delegate_to: "localhost"
  delegate_facts: true