---
dependency:
  name: galaxy
driver:
  name: delegated

platforms:
  - name: centos9-1
    image_name: ansible-dev-centos-9-stream
    groups:
      - docker_manager

  - name: centos9-2
    image_name: ansible-dev-centos-9-stream
    groups:
      - docker_manager

  - name: centos9-3
    image_name: ansible-dev-centos-9-stream
    groups:
      - docker_manager

  - name: centos9-4
    image_name: ansible-dev-centos-9-stream
    groups:
      - docker_worker
provisioner:
  name: ansible
  playbooks:
    create: ../../../setup/molecule/default/create-os.yml
    destroy: ../../../setup/molecule/default/destroy-os.yml
    prepare: ../../../setup/molecule/default-install/converge.yml
    converge: ../default-deploy/converge.yml
    verify: ../default-deploy/verify.yml
verifier:
  name: ansible
