---
dependency:
  name: galaxy
driver:
  name: delegated

platforms:
  - name: centos8-1
    template_name: centos-stream-8
    groups:
      - docker_manager

  - name: centos8-2
    template_name: centos-stream-8
    groups:
      - docker_manager

  - name: centos8-3
    template_name: centos-stream-8
    groups:
      - docker_manager

  - name: centos8-4
    template_name: centos-stream-8
    groups:
      - docker_worker

  - name: centos8-5
    template_name: centos-stream-8
    groups:
      - docker_worker
      - scale_down_host
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    prepare: ../default-install/converge.yml
    destroy: ../default/destroy.yml
    converge: ../default-scaledown/converge.yml
    verify: ../default-scaledown/verify.yml

verifier:
  name: ansible
