---
dependency:
  name: galaxy
driver:
  name: delegated

platforms:
  - name: ubuntu2110-1
    os: ubuntu
    version: 2110
    groups:
      - docker_manager

  - name: ubuntu2110-2
    os: ubuntu
    version: 2110
    groups:
      - docker_manager

  - name: ubuntu2110-3
    os: ubuntu
    version: 2110
    groups:
      - docker_manager

  - name: ubuntu2110-4
    os: ubuntu
    version: 2110
    groups:
      - docker_worker

  - name: ubuntu2110-5
    os: ubuntu
    version: 2110
    groups:
      - docker_worker
      - scale_up_host
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    prepare: ../default-install/converge.yml
    destroy: ../default/destroy.yml
    converge: ../default-scaleup/converge.yml
    verify: ../default-scaleup/verify.yml

verifier:
  name: ansible
