---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: ubuntu2004-1
    template_name: ubuntu-20-04
    groups:
      - docker_manager

  - name: ubuntu2004-2
    template_name: ubuntu-20-04
    groups:
      - docker_manager

  - name: ubuntu2004-3
    template_name: ubuntu-20-04
    groups:
      - docker_manager

  - name: ubuntu2004-4
    template_name: ubuntu-20-04
    groups:
      - docker_worker

  - name: ubuntu2004-5
    template_name: ubuntu-20-04
    groups:
      - docker_worker
      - scale_up_host
      - scale_down_host
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    converge: ../default-install/converge.yml
    verify: ../default-install/verify.yml
verifier:
  name: ansible
