---
- name: Converge - Leave Swarm and Uninstall docker
  hosts: scale_down_host
  gather_facts: yes
  become: yes

  tasks:
    - name: "Include fabos.docker_swarm.setup - uninstall"
      include_role:
        name: setup
        tasks_from: scale_down.yml

    - name: "Include fabos.docker.setup - uninstall"
      include_role:
        name: fabos.docker.setup
        tasks_from: uninstall.yml