---
dependency:
  name: galaxy
driver:
  name: delegated

platforms:
  - name: ubuntu2004-1
    image_name: ansible-dev-ubuntu-20-04
    groups:
      - docker_manager

  - name: ubuntu2004-2
    image_name: ansible-dev-ubuntu-20-04
    groups:
      - docker_manager

  - name: ubuntu2004-3
    image_name: ansible-dev-ubuntu-20-04
    groups:
      - docker_manager

  - name: ubuntu2004-4
    image_name: ansible-dev-ubuntu-20-04
    groups:
      - docker_worker
provisioner:
  name: ansible
  playbooks:
    create: ../default/create-os.yml
    destroy: ../default/destroy-os.yml
    prepare: ../default-install/converge.yml
    converge: ../default-uninstall/converge.yml
    verify: ../default-uninstall/verify.yml

verifier:
  name: ansible
